# NOTE: Generated By HttpRunner v3.1.3
# FROM: har/login.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/")
            .get("https://mubu.com/")
            .with_headers(
                **{
                    "cache-control": "max-age=0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "reg_prepareId": "1738fa2fb30-1738fa2fb2e-4e27-8716-4e64f7a44c7a",
                    "reg_focusId": "dbfdb96e-cd5e-4e27-8716-1738fa30163",
                    "csrf_token": "496a39f8-6d42-4a89-bb66-4c35ad7b6b58",
                    "SESSION": "e22907c6-53f3-460f-b219-82c8775869e7",
                    "_gat": "1",
                    "data-unique-id": "5cec9d20-cff1-11ea-9e64-e5c89e5bd0b5",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595844614",
                    "SLARDAR_WEB_ID": "45b2cc42-71ea-4526-aedb-5a4554da4697",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login")
            .get("https://mubu.com/login")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "reg_prepareId": "1738fa2fb30-1738fa2fb2e-4e27-8716-4e64f7a44c7a",
                    "reg_focusId": "dbfdb96e-cd5e-4e27-8716-1738fa30163",
                    "csrf_token": "496a39f8-6d42-4a89-bb66-4c35ad7b6b58",
                    "SESSION": "e22907c6-53f3-460f-b219-82c8775869e7",
                    "_gat": "1",
                    "data-unique-id": "5cec9d20-cff1-11ea-9e64-e5c89e5bd0b5",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595844627",
                    "SLARDAR_WEB_ID": "fd2f1710-ccde-4adb-b323-6c8f415ddcfa",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login/password")
            .get("https://mubu.com/login/password")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/login",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "csrf_token": "496a39f8-6d42-4a89-bb66-4c35ad7b6b58",
                    "SESSION": "e22907c6-53f3-460f-b219-82c8775869e7",
                    "_gat": "1",
                    "data-unique-id": "5cec9d20-cff1-11ea-9e64-e5c89e5bd0b5",
                    "SLARDAR_WEB_ID": "ee062303-c980-4fb9-bc66-1eb863e4819a",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595844629",
                    "reg_prepareId": "1738fc09340-1738fc092b1-4eaf-884d-b7b579e84250",
                    "reg_focusId": "664198df-9af2-4eaf-884d-1738fc097a6",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/login/submit")
            .post("https://mubu.com/api/login/submit")
            .with_headers(
                **{
                    "content-length": "47",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "csrf_token": "496a39f8-6d42-4a89-bb66-4c35ad7b6b58",
                    "SESSION": "e22907c6-53f3-460f-b219-82c8775869e7",
                    "_gat": "1",
                    "data-unique-id": "5cec9d20-cff1-11ea-9e64-e5c89e5bd0b5",
                    "reg_prepareId": "1738fc09340-1738fc092b1-4eaf-884d-b7b579e84250",
                    "reg_focusId": "664198df-9af2-4eaf-884d-1738fc097a6",
                    "SLARDAR_WEB_ID": "b3ab46ef-6c1f-4b86-893d-5af658013243",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595844631",
                }
            )
            .with_data(
                {"phone": "19945635122", "password": "123456", "remember": "true"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/list")
            .get("https://mubu.com/list")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "csrf_token": "496a39f8-6d42-4a89-bb66-4c35ad7b6b58",
                    "SESSION": "e22907c6-53f3-460f-b219-82c8775869e7",
                    "_gat": "1",
                    "data-unique-id": "5cec9d20-cff1-11ea-9e64-e5c89e5bd0b5",
                    "reg_prepareId": "1738fc09340-1738fc092b1-4eaf-884d-b7b579e84250",
                    "reg_focusId": "664198df-9af2-4eaf-884d-1738fc097a6",
                    "SLARDAR_WEB_ID": "b3ab46ef-6c1f-4b86-893d-5af658013243",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595844631",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MjY1OCIsImV4cCI6MTU5ODQzNjYzMSwiaWF0IjoxNTk1ODQ0NjMxfQ.kUkcPuVPHByqKqaIVVgVFCtMJzIBLvxWSC7tR5TTNDSkJYb6QXIKyQ4lPRffLsrsXrN_NDdg_hjGzyR7jVZXQQ",
                    "user_persistence": "e28a89d6-2288-4247-af6f-d8ac334c870f",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/list/tip_new_update")
            .post("https://mubu.com/api/list/tip_new_update")
            .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
                    "x-requested-with": "XMLHttpRequest",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "csrf_token": "496a39f8-6d42-4a89-bb66-4c35ad7b6b58",
                    "SESSION": "e22907c6-53f3-460f-b219-82c8775869e7",
                    "_gat": "1",
                    "data-unique-id": "5cec9d20-cff1-11ea-9e64-e5c89e5bd0b5",
                    "reg_prepareId": "1738fc09340-1738fc092b1-4eaf-884d-b7b579e84250",
                    "reg_focusId": "664198df-9af2-4eaf-884d-1738fc097a6",
                    "SLARDAR_WEB_ID": "b3ab46ef-6c1f-4b86-893d-5af658013243",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595844631",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MjY1OCIsImV4cCI6MTU5ODQzNjYzMSwiaWF0IjoxNTk1ODQ0NjMxfQ.kUkcPuVPHByqKqaIVVgVFCtMJzIBLvxWSC7tR5TTNDSkJYb6QXIKyQ4lPRffLsrsXrN_NDdg_hjGzyR7jVZXQQ",
                    "user_persistence": "e28a89d6-2288-4247-af6f-d8ac334c870f",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/list/get")
            .post("https://mubu.com/api/list/get")
            .with_headers(
                **{
                    "content-length": "38",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "csrf_token": "496a39f8-6d42-4a89-bb66-4c35ad7b6b58",
                    "SESSION": "e22907c6-53f3-460f-b219-82c8775869e7",
                    "_gat": "1",
                    "data-unique-id": "5cec9d20-cff1-11ea-9e64-e5c89e5bd0b5",
                    "reg_prepareId": "1738fc09340-1738fc092b1-4eaf-884d-b7b579e84250",
                    "reg_focusId": "664198df-9af2-4eaf-884d-1738fc097a6",
                    "SLARDAR_WEB_ID": "b3ab46ef-6c1f-4b86-893d-5af658013243",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595844631",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MjY1OCIsImV4cCI6MTU5ODQzNjYzMSwiaWF0IjoxNTk1ODQ0NjMxfQ.kUkcPuVPHByqKqaIVVgVFCtMJzIBLvxWSC7tR5TTNDSkJYb6QXIKyQ4lPRffLsrsXrN_NDdg_hjGzyR7jVZXQQ",
                    "user_persistence": "e28a89d6-2288-4247-af6f-d8ac334c870f",
                }
            )
            .with_data({"folderId": "0", "sort": "time", "keywords": "", "source": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/message/get_message_unread")
            .post("https://mubu.com/api/message/get_message_unread")
            .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
                    "x-requested-with": "XMLHttpRequest",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "csrf_token": "496a39f8-6d42-4a89-bb66-4c35ad7b6b58",
                    "SESSION": "e22907c6-53f3-460f-b219-82c8775869e7",
                    "_gat": "1",
                    "data-unique-id": "5cec9d20-cff1-11ea-9e64-e5c89e5bd0b5",
                    "reg_prepareId": "1738fc09340-1738fc092b1-4eaf-884d-b7b579e84250",
                    "reg_focusId": "664198df-9af2-4eaf-884d-1738fc097a6",
                    "SLARDAR_WEB_ID": "b3ab46ef-6c1f-4b86-893d-5af658013243",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595844631",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MjY1OCIsImV4cCI6MTU5ODQzNjYzMSwiaWF0IjoxNTk1ODQ0NjMxfQ.kUkcPuVPHByqKqaIVVgVFCtMJzIBLvxWSC7tR5TTNDSkJYb6QXIKyQ4lPRffLsrsXrN_NDdg_hjGzyR7jVZXQQ",
                    "user_persistence": "e28a89d6-2288-4247-af6f-d8ac334c870f",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
