# NOTE: Generated By HttpRunner v3.1.3
# FROM: har/mubu.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMubuLogin(HttpRunner):
    config = Config("mubu login").verify(False).base_url("https://mubu.com") \
        .variables(
        **{
            "host": "mubu.com",
            "phone":"19945635122",
            "password":"123456",


        }
    ).export("unreadCount")

    teststeps = [
        Step(
            RunRequest("/")
                .get("/")
                .with_headers(
                **{
                    "cache-control": "max-age=0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "csrf_token": "496a39f8-6d42-4a89-bb66-4c35ad7b6b58",
                    "data-unique-id": "06787840-cfda-11ea-ad68-83a977aed8cc",
                    "reg_prepareId": "1738f2fb9ee-1738f2fb8f8-4ab3-b653-7b6f07b96880",
                    "reg_focusId": "70c5295d-7961-4ab3-b653-1738f2fc0e9",
                    "SESSION": "a436e48e-855e-4892-a203-54874e66a421",
                    "_gat": "1",
                    "SLARDAR_WEB_ID": "237e52d8-9e86-485a-b615-1203fbaed034",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595835180",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login")
                .get("/login")
                .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "csrf_token": "496a39f8-6d42-4a89-bb66-4c35ad7b6b58",
                    "data-unique-id": "06787840-cfda-11ea-ad68-83a977aed8cc",
                    "reg_prepareId": "1738f2fb9ee-1738f2fb8f8-4ab3-b653-7b6f07b96880",
                    "reg_focusId": "70c5295d-7961-4ab3-b653-1738f2fc0e9",
                    "SESSION": "a436e48e-855e-4892-a203-54874e66a421",
                    "_gat": "1",
                    "SLARDAR_WEB_ID": "6bd0ff08-0228-4901-96e3-6afdcde6493c",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595835194",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login/password")
                .get("/login/password")
                .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/login",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "csrf_token": "496a39f8-6d42-4a89-bb66-4c35ad7b6b58",
                    "SESSION": "a436e48e-855e-4892-a203-54874e66a421",
                    "_gat": "1",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595835196",
                    "reg_prepareId": "1738f30a169-1738f30a098-4e10-8111-7afa34f205b3",
                    "SLARDAR_WEB_ID": "8b975c43-567e-4ebb-8878-4b9ab5920169",
                    "reg_focusId": "147b36a4-86a8-4e10-8111-1738f30a576",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/login/submit")
                .post("/api/login/submit")
                .with_headers(
                **{
                    "content-length": "47",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "csrf_token": "496a39f8-6d42-4a89-bb66-4c35ad7b6b58",
                    "SESSION": "a436e48e-855e-4892-a203-54874e66a421",
                    "_gat": "1",
                    "reg_prepareId": "1738f30a169-1738f30a098-4e10-8111-7afa34f205b3",
                    "reg_focusId": "147b36a4-86a8-4e10-8111-1738f30a576",
                    "SLARDAR_WEB_ID": "0bc637e0-4291-49db-ab05-f7071662fa6d",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595835197",
                }
            )
                .with_data(
                {"phone": "${phone}", "password": "${password}", "remember": "true"}
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
                .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/list")
                .get("/list")
                .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "csrf_token": "496a39f8-6d42-4a89-bb66-4c35ad7b6b58",
                    "SESSION": "a436e48e-855e-4892-a203-54874e66a421",
                    "_gat": "1",
                    "reg_prepareId": "1738f30a169-1738f30a098-4e10-8111-7afa34f205b3",
                    "reg_focusId": "147b36a4-86a8-4e10-8111-1738f30a576",
                    "SLARDAR_WEB_ID": "0bc637e0-4291-49db-ab05-f7071662fa6d",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595835197",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MjY1OCIsImV4cCI6MTU5ODQzNjYzMSwiaWF0IjoxNTk1ODQ0NjMxfQ.kUkcPuVPHByqKqaIVVgVFCtMJzIBLvxWSC7tR5TTNDSkJYb6QXIKyQ4lPRffLsrsXrN_NDdg_hjGzyR7jVZXQQ",
                    "user_persistence": "e28a89d6-2288-4247-af6f-d8ac334c870f",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/list/tip_new_update")
                .post("/api/list/tip_new_update")
                .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-requested-with": "XMLHttpRequest",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "csrf_token": "496a39f8-6d42-4a89-bb66-4c35ad7b6b58",
                    "SESSION": "a436e48e-855e-4892-a203-54874e66a421",
                    "_gat": "1",
                    "reg_prepareId": "1738f30a169-1738f30a098-4e10-8111-7afa34f205b3",
                    "reg_focusId": "147b36a4-86a8-4e10-8111-1738f30a576",
                    "SLARDAR_WEB_ID": "0bc637e0-4291-49db-ab05-f7071662fa6d",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595835197",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MjY1OCIsImV4cCI6MTU5ODQzNjYzMSwiaWF0IjoxNTk1ODQ0NjMxfQ.kUkcPuVPHByqKqaIVVgVFCtMJzIBLvxWSC7tR5TTNDSkJYb6QXIKyQ4lPRffLsrsXrN_NDdg_hjGzyR7jVZXQQ",
                    "user_persistence": "e28a89d6-2288-4247-af6f-d8ac334c870f",
                }
            )
                .with_data("")
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
                .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/list/get")
                .post("/api/list/get")
                .with_headers(
                **{
                    "content-length": "38",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "csrf_token": "496a39f8-6d42-4a89-bb66-4c35ad7b6b58",
                    "SESSION": "a436e48e-855e-4892-a203-54874e66a421",
                    "_gat": "1",
                    "reg_prepareId": "1738f30a169-1738f30a098-4e10-8111-7afa34f205b3",
                    "reg_focusId": "147b36a4-86a8-4e10-8111-1738f30a576",
                    "SLARDAR_WEB_ID": "0bc637e0-4291-49db-ab05-f7071662fa6d",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595835197",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MjY1OCIsImV4cCI6MTU5ODQzNjYzMSwiaWF0IjoxNTk1ODQ0NjMxfQ.kUkcPuVPHByqKqaIVVgVFCtMJzIBLvxWSC7tR5TTNDSkJYb6QXIKyQ4lPRffLsrsXrN_NDdg_hjGzyR7jVZXQQ",
                    "user_persistence": "e28a89d6-2288-4247-af6f-d8ac334c870f",
                }
            )
                .with_data({"folderId": "0", "sort": "time", "keywords": "", "source": ""})
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
                .assert_equal("body.msg", None)

        ),
        Step(
            RunRequest("/api/message/get_message_unread")
                .post("/api/message/get_message_unread")
                .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-requested-with": "XMLHttpRequest",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
                .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "csrf_token": "496a39f8-6d42-4a89-bb66-4c35ad7b6b58",
                    "SESSION": "a436e48e-855e-4892-a203-54874e66a421",
                    "_gat": "1",
                    "reg_prepareId": "1738f30a169-1738f30a098-4e10-8111-7afa34f205b3",
                    "reg_focusId": "147b36a4-86a8-4e10-8111-1738f30a576",
                    "SLARDAR_WEB_ID": "0bc637e0-4291-49db-ab05-f7071662fa6d",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595835197",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MjY1OCIsImV4cCI6MTU5ODQzNjYzMSwiaWF0IjoxNTk1ODQ0NjMxfQ.kUkcPuVPHByqKqaIVVgVFCtMJzIBLvxWSC7tR5TTNDSkJYb6QXIKyQ4lPRffLsrsXrN_NDdg_hjGzyR7jVZXQQ",
                    "user_persistence": "e28a89d6-2288-4247-af6f-d8ac334c870f",
                }
            )
                .with_data("")
                .extract()
                .with_jmespath("body.data.unreadCount", "unreadCount")
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
                .assert_equal("body.msg", None)
        ),]



if __name__ == "__main__":
    TestCaseMubuLogin().test_start()
